Symantec:
  search_link: 'https://www.symantec.com/blogs/threat-intelligence'
  max_timeout: 20
  max_page_limit: 100
  suitable_page_wait_time: 15
  search_action_config:
    click_and_fill_search_box:
      action: 'click and fill'
      element_xpath: '//div[@class="form-item"]//input[@name="search"]'
      element_value: 'google malicious'
    click_search:
      action: 'click'
      element_xpath: '//div[@class="form-submit"]//button'
  page_scrape_config:
    page_links_xpath: '//div[@class="result-items"]//a[@class="blog-teaser__link"]//@href'
    next_page_xpath: '//a[@class="btn btn--more"]//i'
  blog_scrape:
    title_xpath: '//h1//text()'
    date_xpath: '//div[@class="meta"]//time//text()'
    date_format: '%d %b, %Y'
    blog_paragraphs_xpath: '//app-paragraph-rte//text()'
    key_words: 'google,malicious'
Malwarebytes:
  search_link: 'https://blog.malwarebytes.com/?s=google%20malicious'
  max_timeout: 20
  max_page_limit: 100
  suitable_page_wait_time: 5
  page_scrape_config:
    page_links_xpath: '//h2//a//@href'
    next_page_xpath: '//p[@id="pbd-alp-load-posts"]//a'
  blog_scrape:
    title_xpath: '//h1//text()'
    date_xpath: '//div[@id="content"]//p//span//text()'
    date_format: '%B %d, %Y'
    blog_paragraphs_xpath: '//div[@class="post-content"]//text()'
    key_words: 'google,malicious'
Sophos:
  search_link: 'https://nakedsecurity.sophos.com/?s=google+malicious'
  max_timeout: 20
  max_page_limit: 300
  suitable_page_wait_time: 5
  page_scrape_config:
    page_links_xpath: '//h1[@class="result-title"]//a//@href'
    next_page_xpath: '//div[@class="load-more"]//a'
  blog_scrape:
    title_xpath: '//h1[@class="entry-title"]//text()'
    date_xpath: '(//time//@datetime)[1]'
    date_format: '%Y-%m-%d'
    parse_date_string: 10
    blog_paragraphs_xpath: '//div[@class="entry-content"]//text()'
    key_words: 'google,malicious'
KasperkyLab:
  search_link: 'https://www.kaspersky.com/blog/?s=google+malicious'
  max_timeout: 20
  max_page_limit: 300
  suitable_page_wait_time: 5
  search_action_config:
    click_search:
      action: 'click'
      element_xpath: '//p[@class="gdprButton"]'
  page_scrape_config:
    page_links_xpath: '//div[@class="grid-box-content"]//a//@href'
    next_page_xpath: '//button[@id="load-more-posts"]'
  blog_scrape:
    title_xpath: '//h1//text()'
    date_xpath: '//div[@class="single-post-header"]//span[@class="time"]//@content'
    date_format: '%Y-%m-%d'
    blog_paragraphs_xpath: '//div[@class="entry-content post_content"]//text()'
    key_words: 'google,malicious'
Cylance:
  search_link: 'https://threatvector.cylance.com/en_us/search.html?q=google%20malicious&type=threatvector_blog'
  max_timeout: 20
  max_page_limit: 300
  suitable_page_wait_time: 5
  search_action_config:
    click_search:
      action: 'click'
      element_xpath: '//span[@class="cta-btn_outline gdpr-accept"]'
  page_scrape_config:
    page_links_xpath: '//span[@class="title_block"]//a//@href'
    next_page_xpath: '//a[@class="paginate_button next"]'
  blog_scrape:
    title_xpath: '//h1//span//text()'
    date_xpath: '(//div[@class="post_meta"]//text())[3]'
    date_format: '| %B %d, %Y'
    blog_paragraphs_xpath: '//div[@class="cylance-blogs-text"]//text()'
    key_words: 'google,malicious'
CarbonBlack:
  search_link: 'https://www.carbonblack.com/blog/'
  max_timeout: 20
  max_page_limit: 300
  suitable_page_wait_time: 15
  search_action_config:
    click_and_fill_search_box:
      action: 'click and fill'
      scroll: 150
      element_xpath: '//label[@class="input-group"]//input[@id="filter_search"]'
      element_value: 'google malicious'
    click_search:
      action: 'click'
      element_xpath: '//span[@class="input-group-button"]//a'
  page_scrape_config:
    page_links_xpath: '(//div[@class="columns"])[last()]//a//@href'
    next_page_xpath: '//a[@class="next "]'
  blog_scrape:
    title_xpath: '//h2//text()'
    date_xpath: '(//div[@class="columns"]//span//text())[1]'
    date_format: '%B %d, %Y'
    blog_paragraphs_xpath: '//div[@class="columns post-content"]//text()'
    key_words: 'google,malicious'
Fortinet:
  search_link: 'https://www.fortinet.com/blog/search.html?q=google%20malicious'
  max_timeout: 20
  max_page_limit: 300
  suitable_page_wait_time: 5
  search_action_config:
    click_search:
      action: 'click'
      element_xpath: '//div[@id="cookiescript_accept"]'
  page_scrape_config:
    page_links_xpath: '//div[@class="sr-title "]//a//@href'
    next_page_xpath: '//button[@id="btn_load_more"]'
  blog_scrape:
    title_xpath: '//h1//text()'
    date_xpath: '//meta[@property="article:published_time"]//@content'
    date_format: '%Y-%m-%d'
    parse_date_string: 10
    blog_paragraphs_xpath: '//div[@id="sblogs"]//text() | //div[@class="text-container"]//text() | //div[contains(@class,"cmp cmp-text")]//text()'
    key_words: 'google,malicious'
PaloAltoNetworks:
  search_link: 'https://unit42.paloaltonetworks.com/'
  max_timeout: 20
  max_page_limit: 300
  suitable_page_wait_time: 15
  search_action_config:
    click_and_fill_search_box:
      action: 'click and fill'
      element_xpath: '//div[@class="xdsoft_autocomplete"]//input[@form="coveo-dummy-form"]'
      element_value: 'google malicious'
    wait:
      action: 'wait'
      element_value: 5
  page_scrape_config:
    page_links_xpath: '//h3//a//@href'
    next_page_xpath: '(//div[contains(@class, "loadmore")]//button)[2]'
  blog_scrape:
    title_xpath: '//h1//text()'
    date_xpath: '//div[@class="col"]//p//time//@datetime'
    date_format: '%Y-%m-%d'
    parse_date_string: 10
    blog_paragraphs_xpath: '//div[@class="entry-content"]//text()'
    key_words: 'google,malicious'
#Bitdefender: nothing
#CrowdStrike: nothing
#Cylance: nothing
#Cisco: nothing
#FireEye: nothing